# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CodegenBinaries < Formula
  desc "Gen code for AI."
  homepage "https://zeliclabs.com"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zelic91/codegen-binaries/releases/download/v1.0.1/codegen-binaries_Darwin_x86_64.tar.gz"
      sha256 "48551892208d1a58b566a289bf05e2d6253c249a9438d0a64b0b780f5930483a"

      define_method(:install) do
        bin.install "codegen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zelic91/codegen-binaries/releases/download/v1.0.1/codegen-binaries_Darwin_arm64.tar.gz"
      sha256 "a56af601ab73ceb303d5a3136d149aa4041af4e60ca1006766b8f0f567b34191"

      define_method(:install) do
        bin.install "codegen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zelic91/codegen-binaries/releases/download/v1.0.1/codegen-binaries_Linux_x86_64.tar.gz"
      sha256 "e88743639dc328a8eac7cf6b8bf8061938cdae3ba12fe1159ea84c1364cb07fc"
      define_method(:install) do
        bin.install "codegen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zelic91/codegen-binaries/releases/download/v1.0.1/codegen-binaries_Linux_arm64.tar.gz"
      sha256 "fd99d86f74fae18c80747675fd46a693dcfb6b0c11288ab0f779d9f28c03ef69"
      define_method(:install) do
        bin.install "codegen"
      end
    end
  end
end
