# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Codegen < Formula
  desc "Gen code for AI."
  homepage "https://zeliclabs.com"
  version "1.4.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zelic91/codegen-binaries/releases/download/v1.4.2/codegen-binaries_Darwin_x86_64.tar.gz"
      sha256 "d0ac8dcbb03fbbf3dcd798b7e1cea9b5ef418778a3e8b94a066463b1cb69c2ff"

      define_method(:install) do
        bin.install "codegen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zelic91/codegen-binaries/releases/download/v1.4.2/codegen-binaries_Darwin_arm64.tar.gz"
      sha256 "30ea1747daa945d337b8e43a12493834cba8fad2496a13f04e7e465f94faee1d"

      define_method(:install) do
        bin.install "codegen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zelic91/codegen-binaries/releases/download/v1.4.2/codegen-binaries_Linux_x86_64.tar.gz"
      sha256 "3a96b50af6493f958355ad7a309a4624b4fc05f1bf7b73be230ce75ec509c148"
      define_method(:install) do
        bin.install "codegen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zelic91/codegen-binaries/releases/download/v1.4.2/codegen-binaries_Linux_arm64.tar.gz"
      sha256 "95742a76d1f4a1a34cc8f191e54510e57757cdfcf1d586818faeb76d5c3f12ad"
      define_method(:install) do
        bin.install "codegen"
      end
    end
  end
end
