# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Codegen < Formula
  desc "Gen code for AI."
  homepage "https://zeliclabs.com"
  version "1.9.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zelic91/codegen-binaries/releases/download/v1.9.2/codegen-binaries_Darwin_x86_64.tar.gz"
      sha256 "5ef82793513e3c61acb0dd39b2007d6e079ba311fc27b84d5faa95b41d93d214"

      define_method(:install) do
        bin.install "codegen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zelic91/codegen-binaries/releases/download/v1.9.2/codegen-binaries_Darwin_arm64.tar.gz"
      sha256 "c26713864109fb65968ac089d38739a81dc1e169db334392b04085d1d45f68e8"

      define_method(:install) do
        bin.install "codegen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zelic91/codegen-binaries/releases/download/v1.9.2/codegen-binaries_Linux_x86_64.tar.gz"
      sha256 "9298e50f0102f20a7a824dfb1d8ae78db28cb612215d2c409609dd7169c114ae"
      define_method(:install) do
        bin.install "codegen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zelic91/codegen-binaries/releases/download/v1.9.2/codegen-binaries_Linux_arm64.tar.gz"
      sha256 "9bfd545d6bef32d826f3f5e3b8c61071377e96125f5ce5df0a9a91e79208fc10"
      define_method(:install) do
        bin.install "codegen"
      end
    end
  end
end
